[package]
name = "bc-rust"
version = "0.1.0"
edition.workspace = true

[dependencies]
base64.workspace = true
core-interface.workspace = true
factory.workspace = true
hex.workspace = true
hkdf.workspace = true
hmac.workspace = true
rng.workspace = true
sha2.workspace = true
sha3.workspace = true