[package]
name = "cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }

bouncycastle.workspace = true

[[bin]]
name = "bc-rust"
path = "src/main.rs"