[package]
name = "base64"
version = "0.1.0"
edition.workspace = true

[dependencies]
core-interface.workspace = true
utils.workspace = true

[dev-dependencies]
criterion.workspace = true
rng.workspace = true

[[bench]]
name = "base64_benches"
harness = false