[package]
name = "bouncycastle-hex"
version = "0.1.1"
edition.workspace = true

[dependencies]
bouncycastle-utils.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "hex_benches"
harness = false